### PR TITLE
Add base webhook

### PR DESCRIPTION
**Pull request by jaumef**
References: #3 
Added:
- Base Webhook
- Github Webhook
- Gitlab Webhook (init)
- Test data for:
  - Base Webhook
  - Base [github events](https://developer.github.com/v3/activity/events/types/)
  - Base [gitlab events](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md)
- Updated readme
- Added Travis
- Added python requirements
  - Added requirements-dev.txt with mamba
  - Added requirements.txt

---

Tests (using mamba):
- [X] Listener test
  - [X] Instancer by payload
- [X] Webhook test
  - [X] Basic Data
- [x] Gitlab webhook test
  - [x] Basic Data
- [X] Github webhook test
  - [X] Basic Data
  - [X] status

### CODE REVIEW

**Comment by XaviTorello** [comment]
@jaumef good work :)

Just some proposals to integrate on this PR:
- [x] Isolate the class _webhook_ and the dispatcher (the executable, the one that will "proxify" the hooks execution) to provide an easy way to ensure and simplify heritance.
- [x] Provide an extended _webhook_ object to clarify if it works as expected
  - i.e. _github extending _webhook_ defining their own tests and actions to be done
- [x] There are no test data for github hook (at testing test_hooks.py)

What do you think about it?

**Comment by ecarreras** [comment]
@jaumef we need the tests :trollface:

**Comment by XaviTorello** [comment]
Related to #3 and #4
- [x] Provide tests for each hook plz! ^^

**Comment by jaumef** [comment]
@ecarreras @XaviTorello Beware, tests are incoming :+1:

**Comment by XaviTorello** [comment]
Fixes #3 and closes #4 

@jaumef 👍

**Pull request merged**
